import type React from "react";
import type { Metadata } from "next";
import "./globals.css";
import type { JSX } from 'react/jsx-runtime';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-geist antialiased">
        {children}
      </body>
    </html>
  );
}
